import org.jetbrains.compose.desktop.application.dsl.TargetFormat

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.compose.multiplatform)
}

// Read from gradle.properties; CI overrides the version with the tag's.
val versionApp: String = providers.gradleProperty("versionApp").get()
val depotGithub: String = providers.gradleProperty("depotGithub").get()
val clePubliqueMisesAJour: String = providers.gradleProperty("clePubliqueMisesAJour").get()
val licenceApp: String = providers.gradleProperty("licenceApp").get()
/** Android APK certificate fingerprint, read from `TVSlim/gradle.properties` so there is no copy to keep in sync. */
val empreinteCertificat: String = providers.fileContents(layout.projectDirectory.file("../TVSlim/gradle.properties"))
    .asText.get().lineSequence().first { it.startsWith("empreinteCertificat=") }.substringAfter('=').trim()
version = versionApp

/**
 * The Android core, compiled from its own sources: catalogue, engine and safeguards exist once, and
 * their tests run in both builds. `CatalogueRepository.kt` reads its files through an Android
 * `Context`, so it is excluded and replaced by `CatalogueRepositoryJvm.kt`, which reads them from the
 * classpath.
 */
val noyau = layout.projectDirectory.dir("../TVSlim/core")

/** Exposes version and repository to the code without depending on the jpackage launcher. */
val genererInfosApp by tasks.registering {
    val dossier = layout.buildDirectory.dir("generated/infosApp/kotlin")
    val version = versionApp
    val depot = depotGithub
    val clePublique = clePubliqueMisesAJour
    val licence = licenceApp
    val empreinte = empreinteCertificat
    inputs.property("version", version)
    inputs.property("depot", depot)
    inputs.property("clePublique", clePublique)
    inputs.property("licence", licence)
    inputs.property("empreinte", empreinte)
    outputs.dir(dossier)
    doLast {
        val fichier = dossier.get().file("net/jolabs40/tvslim/windows/InfosApp.kt").asFile
        fichier.parentFile.mkdirs()
        fichier.writeText(
            """
            |package net.jolabs40.tvslim.windows
            |
            |/** Generated by the `genererInfosApp` Gradle task, do not edit by hand. */
            |internal object InfosApp {
            |    const val VERSION = "$version"
            |    const val DEPOT_GITHUB = "$depot"
            |    const val CLE_PUBLIQUE_MISES_A_JOUR = "$clePublique"
            |    const val LICENCE = "$licence"
            |    /** Expected certificate of the TV app APK downloaded from GitHub. */
            |    const val EMPREINTE_CERTIFICAT_ANDROID = "$empreinte"
            |}
            |""".trimMargin(),
        )
    }
}

kotlin {
    jvmToolchain(21)
    jvm()

    sourceSets {
        // Strings and icons live in commonMain/composeResources, where Res is generated, so the
        // libraries it calls must be declared there.
        commonMain.dependencies {
            implementation(libs.compose.runtime)
            implementation(libs.compose.foundation)
            implementation(libs.compose.ui)
            implementation(libs.compose.material3)
            implementation(libs.compose.components.resources)
        }
        jvmMain {
            kotlin.srcDir(genererInfosApp)
            kotlin.srcDir(noyau.dir("src/main/java"))
            kotlin.exclude("**/catalog/CatalogueRepository.kt")
            resources.srcDir(noyau.dir("src/main/assets"))

            dependencies {
                implementation(compose.desktop.currentOs)
                implementation(libs.lifecycle.runtime.compose)
                implementation(libs.lifecycle.viewmodel.compose)
                implementation(libs.kotlinx.coroutines.swing)
                implementation(libs.kotlinx.serialization.json)
                implementation(libs.dadb)
                implementation(libs.jmdns)
                implementation(libs.jna.platform)
            }
        }
        jvmTest {
            kotlin.srcDir(noyau.dir("src/test/java"))
            dependencies {
                implementation(libs.junit)
                implementation(libs.kotlinx.coroutines.test)
                implementation(libs.compose.ui.test.junit4)
            }
        }
    }
}

tasks.named<Test>("jvmTest") {
    // TraductionsTest opens `src/main/assets/...` by a relative path, so tests run from the core
    // folder as in the Android build. Windows-only tests work in temp folders and do not care.
    workingDir = noyau.asFile
    // For tests that read the Windows project's own files.
    systemProperty("tvslim.projet", layout.projectDirectory.asFile.absolutePath)
    // Opt-in: screenshots on a real TV, -Pmateriel=192.168.2.135
    providers.gradleProperty("materiel").orNull?.let { systemProperty("tvslim.materiel", it) }
    // Opt-in: logo and card sheet, no TV needed, -Pplanche=1
    providers.gradleProperty("planche").orNull?.let { systemProperty("tvslim.planche", it) }
    // Opt-in, with -Pmateriel: installs a real APK, -Papk=path.apk
    providers.gradleProperty("apk").orNull?.let { systemProperty("tvslim.apk", it) }
    // Opt-in, with -Pmateriel: writes files to the real TV, -Pdepot=1
    providers.gradleProperty("depot").orNull?.let { systemProperty("tvslim.depot", it) }
    // Opt-in, with -Pmateriel: downloads and stores scrcpy, -Pscrcpy=1
    providers.gradleProperty("scrcpy").orNull?.let { systemProperty("tvslim.scrcpy", it) }
    // Opt-in, with -Pmateriel: updates the TV app from GitHub, -PapplicationTv=1
    providers.gradleProperty("applicationTv").orNull?.let { systemProperty("tvslim.applicationtv", it) }
    // Opt-in: runs the real update relay, -PrelaisMsi=... -PrelaisExe=...
    providers.gradleProperty("relaisMsi").orNull?.let { systemProperty("tvslim.relais.msi", it) }
    providers.gradleProperty("relaisExe").orNull?.let { systemProperty("tvslim.relais.exe", it) }
    providers.gradleProperty("relaisPid").orNull?.let { systemProperty("tvslim.relais.pid", it) }
    systemProperty("tvslim.captures", layout.buildDirectory.dir("captures").get().asFile.absolutePath)
    useJUnit()
}

compose.resources {
    packageOfResClass = "net.jolabs40.tvslim.windows.ressources"
    publicResClass = false
    generateResClass = always
}

/** Android Studio's JBR has no jpackage, so the installer is built with the Adoptium JDK. */
val jdkPaquetage = javaToolchains.launcherFor {
    languageVersion = JavaLanguageVersion.of(21)
    vendor = JvmVendorSpec.ADOPTIUM
}

compose.desktop {
    application {
        mainClass = "net.jolabs40.tvslim.windows.MainKt"
        javaHome = jdkPaquetage.get().metadata.installationPath.asFile.absolutePath

        nativeDistributions {
            targetFormats(TargetFormat.Msi)
            packageName = "TV Slim"
            packageVersion = versionApp
            description = "Reversible debloat for Android TV"
            vendor = "jolabs40"
            copyright = "jolabs40"

            // What `suggestRuntimeModules` lists, plus what no dependency analysis sees: Ed25519 and
            // TLS (jdk.crypto.ec), French month names (jdk.localedata), screen readers (jdk.accessibility).
            modules(
                "java.instrument",
                "java.net.http",
                "jdk.unsupported",
                "jdk.crypto.ec",
                "jdk.localedata",
                "jdk.accessibility",
            )

            windows {
                iconFile.set(project.file("packaging/tvslim.ico"))
                // Never change: it makes a new version replace the old one instead of installing
                // alongside it.
                upgradeUuid = "b2c131f4-d4d2-415b-980e-57b089c14718"
                // Per-user install: no admin rights, no UAC prompt, so auto-updates run silently.
                perUserInstall = true
                dirChooser = false
                menu = true
                menuGroup = "TV Slim"
                shortcut = true
            }
        }
    }
}
