import org.jetbrains.compose.desktop.application.dsl.TargetFormat

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.compose.multiplatform)
}

// Read from gradle.properties; CI overrides the version with the tag's.
val appVersion: String = providers.gradleProperty("appVersion").get()
val githubRepository: String = providers.gradleProperty("githubRepository").get()
val updatesPublicKey: String = providers.gradleProperty("updatesPublicKey").get()
val appLicense: String = providers.gradleProperty("appLicense").get()
/** Android APK certificate fingerprint, read from `TVSlim/gradle.properties` so there is no copy to keep in sync. */
val certificateFingerprint: String = providers.fileContents(layout.projectDirectory.file("../TVSlim/gradle.properties"))
    .asText.get().lineSequence().first { it.startsWith("certificateFingerprint=") }.substringAfter('=').trim()
version = appVersion

/**
 * The Android core, compiled from its own sources: catalogue, engine and safeguards exist once, and
 * their tests run in both builds. `CatalogRepository.kt` reads its files through an Android
 * `Context`, so it is excluded and replaced by `CatalogRepositoryJvm.kt`, which reads them from the
 * classpath.
 */
val core = layout.projectDirectory.dir("../TVSlim/core")

/** Exposes version and repository to the code without depending on the jpackage launcher. */
val generateAppInfo by tasks.registering {
    val folder = layout.buildDirectory.dir("generated/infosApp/kotlin")
    val version = appVersion
    val repository = githubRepository
    val publicKeyBase64 = updatesPublicKey
    val license = appLicense
    val fingerprint = certificateFingerprint
    inputs.property("version", version)
    inputs.property("repository", repository)
    inputs.property("clePublique", publicKeyBase64)
    inputs.property("licence", license)
    inputs.property("empreinte", fingerprint)
    outputs.dir(folder)
    doLast {
        val file = folder.get().file("net/jolabs40/tvslim/windows/AppInfo.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |package net.jolabs40.tvslim.windows
            |
            |/** Generated by the `generateAppInfo` Gradle task, do not edit by hand. */
            |internal object AppInfo {
            |    const val VERSION = "$version"
            |    const val GITHUB_REPOSITORY = "$repository"
            |    const val UPDATE_PUBLIC_KEY = "$publicKeyBase64"
            |    const val LICENSE = "$license"
            |    /** Expected certificate of the TV app APK downloaded from GitHub. */
            |    const val ANDROID_CERTIFICATE_FINGERPRINT = "$fingerprint"
            |}
            |""".trimMargin(),
        )
    }
}

kotlin {
    jvmToolchain(21)
    jvm()

    sourceSets {
        // Strings and icons live in commonMain/composeResources, where Res is generated, so the
        // libraries it calls must be declared there.
        commonMain.dependencies {
            implementation(libs.compose.runtime)
            implementation(libs.compose.foundation)
            implementation(libs.compose.ui)
            implementation(libs.compose.material3)
            implementation(libs.compose.components.resources)
        }
        jvmMain {
            kotlin.srcDir(generateAppInfo)
            kotlin.srcDir(core.dir("src/main/java"))
            kotlin.exclude("**/catalog/CatalogRepository.kt")
            resources.srcDir(core.dir("src/main/assets"))

            dependencies {
                implementation(compose.desktop.currentOs)
                implementation(libs.lifecycle.runtime.compose)
                implementation(libs.lifecycle.viewmodel.compose)
                implementation(libs.kotlinx.coroutines.swing)
                implementation(libs.kotlinx.serialization.json)
                implementation(libs.dadb)
                implementation(libs.jmdns)
                implementation(libs.jna.platform)
            }
        }
        jvmTest {
            kotlin.srcDir(core.dir("src/test/java"))
            dependencies {
                implementation(libs.junit)
                implementation(libs.kotlinx.coroutines.test)
                implementation(libs.compose.ui.test.junit4)
            }
        }
    }
}

tasks.named<Test>("jvmTest") {
    // TraductionsTest opens `src/main/assets/...` by a relative path, so tests run from the core
    // folder as in the Android build. Windows-only tests work in temp folders and do not care.
    workingDir = core.asFile
    // For tests that read the Windows project's own files.
    systemProperty("tvslim.project", layout.projectDirectory.asFile.absolutePath)
    // Opt-in: screenshots on a real TV, -Phardware=192.168.2.135
    providers.gradleProperty("hardware").orNull?.let { systemProperty("tvslim.hardware", it) }
    // Opt-in: logo and card sheet, no TV needed, -Pplanche=1
    providers.gradleProperty("logoSheet").orNull?.let { systemProperty("tvslim.logoSheet", it) }
    // Opt-in, with -Phardware: installs a real APK, -Papk=path.apk
    providers.gradleProperty("apk").orNull?.let { systemProperty("tvslim.apk", it) }
    // Opt-in, with -Phardware: writes files to the real TV, -Pupload=1
    providers.gradleProperty("upload").orNull?.let { systemProperty("tvslim.upload", it) }
    // Opt-in, with -Phardware: downloads and stores scrcpy, -Pscrcpy=1
    providers.gradleProperty("scrcpy").orNull?.let { systemProperty("tvslim.scrcpy", it) }
    // Opt-in, with -Phardware: updates the TV app from GitHub, -PtvApp=1
    providers.gradleProperty("tvApp").orNull?.let { systemProperty("tvslim.tvApp", it) }
    // Opt-in: runs the real update relay, -PrelaisMsi=... -PrelaisExe=...
    providers.gradleProperty("relayMsi").orNull?.let { systemProperty("tvslim.relay.msi", it) }
    providers.gradleProperty("relayExe").orNull?.let { systemProperty("tvslim.relay.exe", it) }
    providers.gradleProperty("relayPid").orNull?.let { systemProperty("tvslim.relay.pid", it) }
    systemProperty("tvslim.captures", layout.buildDirectory.dir("captures").get().asFile.absolutePath)
    useJUnit()
}

compose.resources {
    packageOfResClass = "net.jolabs40.tvslim.windows.resources"
    publicResClass = false
    generateResClass = always
}

/** Android Studio's JBR has no jpackage, so the installer is built with the Adoptium JDK. */
val packagingJdk = javaToolchains.launcherFor {
    languageVersion = JavaLanguageVersion.of(21)
    vendor = JvmVendorSpec.ADOPTIUM
}

compose.desktop {
    application {
        mainClass = "net.jolabs40.tvslim.windows.MainKt"
        javaHome = packagingJdk.get().metadata.installationPath.asFile.absolutePath

        nativeDistributions {
            targetFormats(TargetFormat.Msi)
            packageName = "TV Slim"
            packageVersion = appVersion
            description = "Reversible debloat for Android TV"
            vendor = "jolabs40"
            copyright = "jolabs40"

            // What `suggestRuntimeModules` lists, plus what no dependency analysis sees: Ed25519 and
            // TLS (jdk.crypto.ec), French month names (jdk.localedata), screen readers (jdk.accessibility).
            modules(
                "java.instrument",
                "java.net.http",
                "jdk.unsupported",
                "jdk.crypto.ec",
                "jdk.localedata",
                "jdk.accessibility",
            )

            windows {
                iconFile.set(project.file("packaging/tvslim.ico"))
                // Never change: it makes a new version replace the old one instead of installing
                // alongside it.
                upgradeUuid = "b2c131f4-d4d2-415b-980e-57b089c14718"
                // Per-user install: no admin rights, no UAC prompt, so auto-updates run silently.
                perUserInstall = true
                dirChooser = false
                menu = true
                menuGroup = "TV Slim"
                shortcut = true
            }
        }
    }
}
